[package]
name = "egui_autocomplete"
version = "0.1.0"
edition = "2021"


[dependencies]
fuzzy-matcher = "*"
egui = { version = "0.22", default-features = false }

[dev-dependencies]
eframe = { version = "0.22", default-features = false, features = [
   "default_fonts",
   "glow",
] }
